version: "3.8"
services:

  gateway:
    image: nginx:1.19.8-alpine
    ports:
      - 8080:8080
    networks:
      - backend
    volumes:
      - ./Gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./Gateway/api_gateway.conf:/etc/nginx/api_gateway.conf
      
  user-service:
    image: userservice:compose_build
    build:
      context: ./user-service
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${USER_SERVICE_PORT}
      MONGODB_URI: mongo:27017
    restart: always
      
  ticket-service:
    image: ticketservice:compose_build
    build:
      context: ./ticket-service
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      USER_SERVICE_DOMAIN: ${USER_SERVICE_DOMAIN}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      FLIGHT_SERVICE_DOMAIN: ${FLIGHT_SERVICE_DOMAIN}
      FLIGHT_SERVICE_PORT: ${FLIGHT_SERVICE_PORT}
      PORT: ${TICKET_SERVICE_PORT}

  flight-service:
    image: flightservice:compose_build
    build:
      context: ./flight-service
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${FLIGHT_SERVICE_PORT}

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

networks:
  backend:
    name: booking
    driver: bridge
