version: "3.8"
services:

  gateway:
    image: nginx:1.19.8-alpine
    ports:
      - 8080:8080
    networks:
      - backend
    volumes:
      - ./Gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./Gateway/api_gateway.conf:/etc/nginx/api_gateway.conf
      
  user-service:
    image: user-service:compose_build
    build:
      context: ./user-service
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${USER_SERVICE_PORT}
      
  ticket-service:
    image: ticket-service:compose_build
    build:
      context: ./ticket-service
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      USER_SERVICE_DOMAIN: ${USER_SERVICE_DOMAIN}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      FLIGHT_SERVICE_DOMAIN: ${FLIGHT_SERVICE_DOMAIN}
      FLIGHT_SERVICE_PORT: ${FLIGHT_SERVICE_PORT}
      PORT: ${TICKET_SERVICE_PORT}

  flight-service:
    image: flight-service:compose_build
    build:
      context: ./flight-service
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${FLIGHT_SERVICE_PORT}


networks:
  backend:
    name: booking
    driver: bridge
