// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.2
// source: freeSeatsService.proto

package freeSeats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FreeSeats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlightId          string `protobuf:"bytes,1,opt,name=flightId,proto3" json:"flightId,omitempty"`
	NumberOfFreeSeats uint64 `protobuf:"varint,2,opt,name=numberOfFreeSeats,proto3" json:"numberOfFreeSeats,omitempty"`
}

func (x *FreeSeats) Reset() {
	*x = FreeSeats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freeSeatsService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FreeSeats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreeSeats) ProtoMessage() {}

func (x *FreeSeats) ProtoReflect() protoreflect.Message {
	mi := &file_freeSeatsService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreeSeats.ProtoReflect.Descriptor instead.
func (*FreeSeats) Descriptor() ([]byte, []int) {
	return file_freeSeatsService_proto_rawDescGZIP(), []int{0}
}

func (x *FreeSeats) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *FreeSeats) GetNumberOfFreeSeats() uint64 {
	if x != nil {
		return x.NumberOfFreeSeats
	}
	return 0
}

type GetFreeSeatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlightId string `protobuf:"bytes,1,opt,name=flightId,proto3" json:"flightId,omitempty"`
}

func (x *GetFreeSeatsRequest) Reset() {
	*x = GetFreeSeatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freeSeatsService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFreeSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFreeSeatsRequest) ProtoMessage() {}

func (x *GetFreeSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_freeSeatsService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFreeSeatsRequest.ProtoReflect.Descriptor instead.
func (*GetFreeSeatsRequest) Descriptor() ([]byte, []int) {
	return file_freeSeatsService_proto_rawDescGZIP(), []int{1}
}

func (x *GetFreeSeatsRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

type GetFreeSeatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FreeSeats *FreeSeats `protobuf:"bytes,1,opt,name=freeSeats,proto3" json:"freeSeats,omitempty"`
}

func (x *GetFreeSeatsResponse) Reset() {
	*x = GetFreeSeatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_freeSeatsService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFreeSeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFreeSeatsResponse) ProtoMessage() {}

func (x *GetFreeSeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_freeSeatsService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFreeSeatsResponse.ProtoReflect.Descriptor instead.
func (*GetFreeSeatsResponse) Descriptor() ([]byte, []int) {
	return file_freeSeatsService_proto_rawDescGZIP(), []int{2}
}

func (x *GetFreeSeatsResponse) GetFreeSeats() *FreeSeats {
	if x != nil {
		return x.FreeSeats
	}
	return nil
}

var File_freeSeatsService_proto protoreflect.FileDescriptor

var file_freeSeatsService_proto_rawDesc = []byte{
	0x0a, 0x16, 0x66, 0x72, 0x65, 0x65, 0x53, 0x65, 0x61, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x55, 0x0a, 0x09, 0x46, 0x72, 0x65, 0x65,
	0x53, 0x65, 0x61, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x49,
	0x64, 0x12, 0x2c, 0x0a, 0x11, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x46, 0x72, 0x65,
	0x65, 0x53, 0x65, 0x61, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x11, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x46, 0x72, 0x65, 0x65, 0x53, 0x65, 0x61, 0x74, 0x73, 0x22,
	0x31, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x46, 0x72, 0x65, 0x65, 0x53, 0x65, 0x61, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x49, 0x64, 0x22, 0x40, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x46, 0x72, 0x65, 0x65, 0x53, 0x65, 0x61,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x09, 0x66, 0x72,
	0x65, 0x65, 0x53, 0x65, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x46, 0x72, 0x65, 0x65, 0x53, 0x65, 0x61, 0x74, 0x73, 0x52, 0x09, 0x66, 0x72, 0x65, 0x65, 0x53,
	0x65, 0x61, 0x74, 0x73, 0x32, 0x51, 0x0a, 0x10, 0x46, 0x72, 0x65, 0x65, 0x53, 0x65, 0x61, 0x74,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x46,
	0x72, 0x65, 0x65, 0x53, 0x65, 0x61, 0x74, 0x73, 0x12, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x72,
	0x65, 0x65, 0x53, 0x65, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x47, 0x65, 0x74, 0x46, 0x72, 0x65, 0x65, 0x53, 0x65, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x66, 0x72, 0x65, 0x65, 0x53, 0x65, 0x61, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_freeSeatsService_proto_rawDescOnce sync.Once
	file_freeSeatsService_proto_rawDescData = file_freeSeatsService_proto_rawDesc
)

func file_freeSeatsService_proto_rawDescGZIP() []byte {
	file_freeSeatsService_proto_rawDescOnce.Do(func() {
		file_freeSeatsService_proto_rawDescData = protoimpl.X.CompressGZIP(file_freeSeatsService_proto_rawDescData)
	})
	return file_freeSeatsService_proto_rawDescData
}

var file_freeSeatsService_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_freeSeatsService_proto_goTypes = []interface{}{
	(*FreeSeats)(nil),            // 0: FreeSeats
	(*GetFreeSeatsRequest)(nil),  // 1: GetFreeSeatsRequest
	(*GetFreeSeatsResponse)(nil), // 2: GetFreeSeatsResponse
}
var file_freeSeatsService_proto_depIdxs = []int32{
	0, // 0: GetFreeSeatsResponse.freeSeats:type_name -> FreeSeats
	1, // 1: FreeSeatsService.GetFreeSeats:input_type -> GetFreeSeatsRequest
	2, // 2: FreeSeatsService.GetFreeSeats:output_type -> GetFreeSeatsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_freeSeatsService_proto_init() }
func file_freeSeatsService_proto_init() {
	if File_freeSeatsService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_freeSeatsService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FreeSeats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freeSeatsService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFreeSeatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_freeSeatsService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFreeSeatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_freeSeatsService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_freeSeatsService_proto_goTypes,
		DependencyIndexes: file_freeSeatsService_proto_depIdxs,
		MessageInfos:      file_freeSeatsService_proto_msgTypes,
	}.Build()
	File_freeSeatsService_proto = out.File
	file_freeSeatsService_proto_rawDesc = nil
	file_freeSeatsService_proto_goTypes = nil
	file_freeSeatsService_proto_depIdxs = nil
}
