// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.2
// source: freeSeatsService.proto

package freeSeats

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FreeSeatsServiceClient is the client API for FreeSeatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FreeSeatsServiceClient interface {
	GetFreeSeats(ctx context.Context, in *GetFreeSeatsRequest, opts ...grpc.CallOption) (*GetFreeSeatsResponse, error)
}

type freeSeatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFreeSeatsServiceClient(cc grpc.ClientConnInterface) FreeSeatsServiceClient {
	return &freeSeatsServiceClient{cc}
}

func (c *freeSeatsServiceClient) GetFreeSeats(ctx context.Context, in *GetFreeSeatsRequest, opts ...grpc.CallOption) (*GetFreeSeatsResponse, error) {
	out := new(GetFreeSeatsResponse)
	err := c.cc.Invoke(ctx, "/FreeSeatsService/GetFreeSeats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FreeSeatsServiceServer is the server API for FreeSeatsService service.
// All implementations must embed UnimplementedFreeSeatsServiceServer
// for forward compatibility
type FreeSeatsServiceServer interface {
	GetFreeSeats(context.Context, *GetFreeSeatsRequest) (*GetFreeSeatsResponse, error)
	mustEmbedUnimplementedFreeSeatsServiceServer()
}

// UnimplementedFreeSeatsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFreeSeatsServiceServer struct {
}

func (UnimplementedFreeSeatsServiceServer) GetFreeSeats(context.Context, *GetFreeSeatsRequest) (*GetFreeSeatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFreeSeats not implemented")
}
func (UnimplementedFreeSeatsServiceServer) mustEmbedUnimplementedFreeSeatsServiceServer() {}

// UnsafeFreeSeatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FreeSeatsServiceServer will
// result in compilation errors.
type UnsafeFreeSeatsServiceServer interface {
	mustEmbedUnimplementedFreeSeatsServiceServer()
}

func RegisterFreeSeatsServiceServer(s grpc.ServiceRegistrar, srv FreeSeatsServiceServer) {
	s.RegisterService(&FreeSeatsService_ServiceDesc, srv)
}

func _FreeSeatsService_GetFreeSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFreeSeatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeSeatsServiceServer).GetFreeSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FreeSeatsService/GetFreeSeats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeSeatsServiceServer).GetFreeSeats(ctx, req.(*GetFreeSeatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FreeSeatsService_ServiceDesc is the grpc.ServiceDesc for FreeSeatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FreeSeatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FreeSeatsService",
	HandlerType: (*FreeSeatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFreeSeats",
			Handler:    _FreeSeatsService_GetFreeSeats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "freeSeatsService.proto",
}
